### ISSUE TITLE
Link text is incorrect if no preview was found

### ISSUE THREAD

**Issue by chustedde** [AriGonzo/secretSanta#1]
How to replicate:

1. Add an item with a link that has a preview
1. Add another item with a link where no link preview is found

The link will be correct when the item is clicked, but the link preview text will be from the previous link added.

The eShop link was added first:
![microsoftteams-image 4](https://user-images.githubusercontent.com/1918659/33560105-c7f89b00-d8dc-11e7-979d-a8a511bbbbc9.png)

Then the Ringly strap link was added, but no preview was available, so it used the text from the eShop link:
![microsoftteams-image 5](https://user-images.githubusercontent.com/1918659/33560107-c9f67152-d8dc-11e7-8c5d-12096b3da392.png)

**Comment by AriGonzo** [comment]
Thanks @chustedde! I caught this last night and it _should_ be fixed now. I wasn't resetting the state of the modal on close when it came to the metadata so if it wasn't overwritten, it was carrying over the previous entry's metadata. 

I cleaned up the DB and anyone who added a wish that had the wrong metadata _should_ be fixed now. If there's any other issues please let me know!
